### ISSUE TITLE
Add missing type array if items present

### ISSUE THREAD

**Issue by jayvdb** [pglass/py-openapi-schema-to-json-schema#13]
It doesnt appear to be explicit that `type` is required on Openapi Schema Object or JSON Schema @ https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.7.6.1

However as seen at https://github.com/pglass/py-openapi-schema-to-json-schema/issues/10 , an explicit `type` can be quite important.  But if we can explicitly add an implicit `type: array`, we could sensibly also be able to add `type: ['array', 'null']`.

From https://spec.openapis.org/oas/v3.0.3#properties

> items - Value MUST be an object and not an array. Inline or referenced schema MUST be of a Schema Object and not a standard JSON Schema. items MUST be present if the type is array.

Therefore, if `items` is present, can `type: array` be added if it is missing?

Looking through the examples in the spec, I see none where `items` is used and `type: array` is not present.

Are there other schema where `items` is valid?

**Comment by jayvdb** [comment]
Likewise if `enum` is present, and no `type` is present, can the `type` be inferred by collating all of the types of the enum values?

OpenAPI defers to [JSON Schema on enum](https://tools.ietf.org/html/draft-wright-json-schema-validation-00#section-5.20)

According to that, it is possible to add `null` to the enum, which would be another approach.

**Comment by pglass** [comment]
Minor clarification, this library converts to JSON Schema Draft 4 (not the same as the 2019-09 draft):
* https://json-schema.org/specification-links.html#draft-4

Per [JSON Schema Draft 4 validation rules](https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.3), 
* `items` can be present in a JSON Schema without `array` and vice versa. They even give an example of `items` without `type`.
* Also, OpenAPI says `type: array` requires `items`, but that doesn't mean `items` requires `type: array` in an OpenAPI Schema.

Given that, it seems a bit wrong to force `type: array` whenever `items` is used. It seems reasonable to include `type: array` in the resulting JSON Schema only if the user has specified it in the OpenAPI Schema. 

Likewise with `enum`, given that JSON Schema allows `enum` without `type`, I'd rather not force a `type` list. For example, it may be that some users of this library convert from OpenAPI Schema to JSON Schema one time, and then commit those JSON Schemas somewhere and maintain them. If they need to add additional enum values, they would have to manually update the type list.
