### ISSUE TITLE
Document support

### ISSUE THREAD

**Issue by jayvdb** [pglass/py-openapi-schema-to-json-schema#8]
Currently there is no handling for complete openapi documents.

Is this an appropriate direction to go in?

I've done some preliminary work, and will post a PR for consideration/ starting the ball rolling.

**Comment by pglass** [comment]
Overall, I'm generally not in favor, though not entirely against.

* It adds complexity which does not have to exist here. Full document processing can be done externally (right?). I've already punted on support for `$ref` fields, for example, which also must be handled externally.
* [OpenAPI 3.1 will fully support JSON Schema](https://www.openapis.org/blog/2020/06/18/openapi-3-1-0-rc0-its-here), from what I understand, so this library will eventually become obsolete (emphasis on "eventually").
  * [Here is an explanatory post](https://apisyouwonthate.com/blog/openapi-v31-and-json-schema-2019-09) on this by Phil Sturgeon. 
  * However, OpenAPI 3.1 is still in RC and [the tooling support for JSON Schema 2019-09 isn't yet there in Python](https://github.com/Julian/jsonschema/issues/613), so it will be some time before this is a viable alternative.
